---
- name: Install Apache and Deploy Custom WebPage on All App Servers
  hosts: all
  become: true

  tasks:
    - name: Install Apache httpd package
      package:
        name: httpd
        state: present
    - name: Ensure Apache httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
    - name: Deploy custom index.html file
      copy: 
        dest: /var/www/html/index.html
        content: "This is a Nautilus sample file, created using Ansible!"
        owner: apache
        group: apache
        mode: '0644'
    - name: Add Heading to index.html
      lineinfile:
         path: /var/www/html/index.html
         line: "Welcome to Nautilus Group!"
         insertafter: BOF
         owner: apache
         group: apache
         mode: '0644'